version: "3.9"

services:

  backend:
    build: .
    command: bash -c "gunicorn project.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000

  web_server:
    build: ./nginx
    ports:
      - 80:80
